apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cf62770f9-dotnet-basic
  janus-idp.io/tekton: cf62770f9-dotnet-basic
  backstage.io/kubernetes-id: cf62770f9-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cf62770f9-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
